apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pr-test
  annotations:
    pipelinesascode.tekton.dev/on-comment: "^((/test-all)|(/build-test))$"
    pipelinesascode.tekton.dev/task: '[.tekton/git-version.yaml,.tekton/git-clone.yaml]'
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[incoming]"
    pipelinesascode.tekton.dev/on-target-branch: "[main**]"
    pipelinesascode.tekton.dev/on-cel-expression: |-
      (
        ".tekton/pr-test.yaml".pathChanged() ||
        last_commit_title.contains("Auto-commit")
      ) && ((
        event == "push" && (
          source_branch.matches("^(main|master|release-.*)$") ||
          target_branch.matches("^(main|master|release-.*)$") ||
          target_branch.startsWith("refs/tags/")
        )
      ) || (
        event == "pull_request" && (
          target_branch.matches("^(main|master|release-.*)$")
        )
      ))
spec:
  pipelineSpec:
    params:
      - name: tips
        default: "This is a test pipeline"
    tasks:
      - name: hello
        taskSpec:
          steps:
            - name: hello
              image: registry.alauda.cn:60080/ops/ubuntu:latest
              script: |
                #!/bin/bash
                echo "$(params.tips)"

      - name: git-clone
        timeout: 10m
        retries: 3
        taskRef:
          name: git-clone

        params:
          - name: url
            value: $(params.git-url)
          - name: revision
            value: $(params.git-revision)

        workspaces:
          - name: output
            workspace: source
          - name: basic-auth
            workspace: basic-auth

      - name: git-version
        runAfter:
          - git-clone
        params:
          - name: gitversion-image
            value: registry.alauda.cn:60080/devops/gittools/gitversion:6.0.5
          - name: yq-image
            value: registry.alauda.cn:60080/devops/noroot/yq:latest
        taskRef:
          name: git-version
        timeout: 10m0s
        retries: 3
        workspaces:
          - name: source
            workspace: source
          - name: basic-auth
            workspace: basic-auth

  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: git-revision
      value: "{{ source_branch }}"
    - name: git-commit
      value: "{{ revision }}"

    # 用于更新 values.yaml 中指定制品的版本
    # 例如: ".global.images.ui.tag=latest,.global.images.api.tag=latest"
    - name: tips
      value: "{{ overwrite_artifacts }}"

  workspaces:
    # This secret will be replaced by the pac controller
    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
